# Generated by Django 6.0 on 2025-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default=1, help_text="Укажите номер телефона", max_length=150, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
    ]
