# Generated by Django 6.0 on 2025-12-13 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_name",
                    models.CharField(help_text="Укажите Имя автора", max_length=30, verbose_name="Имя автора"),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Укажите Фамилию автора", max_length=30, verbose_name="Фамилия автора"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Укажите Отчество автора",
                        max_length=30,
                        null=True,
                        verbose_name="Отчество автора",
                    ),
                ),
                ("date_create", models.DateField(auto_now_add=True, verbose_name="Дата создания записи об авторе")),
                ("date_update", models.DateField(auto_now=True, verbose_name="Дата изменения записи об авторе")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Укажите название", max_length=150, verbose_name="Название")),
                ("year", models.DateField(help_text="Укажите дату выхода книги", verbose_name="Дата выхода книги")),
                ("date_create", models.DateField(auto_now_add=True, verbose_name="Дата создания записи о книге")),
                ("date_update", models.DateField(auto_now=True, verbose_name="Дата изменения записи о книге")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Укажите автора",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book+",
                        to="library_management.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
