# Generated by Django 6.0 on 2025-12-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookIssuance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "book_issued",
                    models.BooleanField(
                        default=True, help_text="Укажите признак выдачи книги", verbose_name="Признак выдачи книги"
                    ),
                ),
                (
                    "book_returned",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите признак возврата книги",
                        verbose_name="Признак возврата книги",
                    ),
                ),
                (
                    "date_create",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания записи о выдачи книги"),
                ),
                ("date_update", models.DateField(auto_now=True, verbose_name="Дата изменения записи о выдачи книги")),
                ("date_return", models.DateField(blank=True, null=True, verbose_name="Дата возврата книги")),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Укажите название книги",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_issuance+",
                        to="library_management.book",
                        verbose_name="Название Книги",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Укажите владельца",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_issuance+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_issuance+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача книг",
                "verbose_name_plural": "Выдача книг",
            },
        ),
    ]
